# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0f0ef95aaeb89fb2f90df6939e5ecd54f19631efc44253a7e3b036d2c403287aa790d5a02fbe4d5592650f17dd1fbb89a055f683a25926cc2003efedf62e202c

test:
  secret_key_base: 7b5e38f3157c84fe89a83916e4710ff47a67a06a5bd74ce0dc1beabb3d3c0b289e9833fb386b646ce593d401cb9a0acbc729df248881b4eab6a64bcda883d73c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
